### ISSUE TITLE
Can not view mentioned places in stories

### ISSUE THREAD

**Issue by i4081i** [austinhuang0131/barinsta#1001]
New Trace collected: 
===================== 
IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues. 
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation. 
 
Error report collected on: Thu Apr 08 15:44:04 GMT+03:00 2021 
 
Information: 
============== 
VERSION  : 19.1.0 
VERSION_CODE : 60 
PHONE-MODEL : SNE-LX1 
ANDROID_VERS : 10 
ANDROID_REL : 29 
BRAND   : HUAWEI 
MANUFACTURER : HUAWEI 
BOARD   : SNE 
DEVICE   : HWSNE 
PRODUCT  : SNE-LX1 
HOST   : cn-central-1b-2d99f2d101595983260308-672168572-32bbf 
TAGS   : release-keys 
 
Stack: 
============== 
java.lang.NumberFormatException: For input string: "Самара" 
 at java.lang.Long.parseLong(Long.java:594) 
 at java.lang.Long.parseLong(Long.java:636) 
 at awais.instagrabber.fragments.-$$Lambda$StoryViewerFragment$AZSiLOFQO2D4HZVZA9CfXm_rFSQ.onClick(lambda:22) 
 at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1) 
 at android.widget.AdapterView.performItemClick(AdapterView.java:330) 
 at android.widget.AbsListView.performItemClick(AbsListView.java:1259) 
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3306) 
 at android.widget.AbsListView$3.run(AbsListView.java:4296) 
 at android.os.Handler.handleCallback(Handler.java:888) 
 at android.os.Handler.dispatchMessage(Handler.java:100) 
 at android.os.Looper.loop(Looper.java:213) 
 at android.app.ActivityThread.main(ActivityThread.java:8178) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
 
Cause: 
============== 
 
**** End of current Report ***

**Comment by austinhuang0131** [comment]
please update to v19.2.0
