### ISSUE TITLE
[BUG] IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled

### ISSUE THREAD

**Issue by ammargitham** [austinhuang0131/barinsta#1202]
From #1199

New Trace collected:

IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: Sat Mar 27 11:14:12 GMT+05:30 2021
Information:

VERSION : 19.1.0
VERSION_CODE : 60
PHONE-MODEL : vivo 1610
ANDROID_VERS : 6.0.1
ANDROID_REL : 23
BRAND : vivo
MANUFACTURER : vivo
BOARD : QC_Reference_Phone
DEVICE : 1610
PRODUCT : 1610
HOST : compiler026
TAGS : release-keys
Stack:

java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: DirectInboxItemViewHolder{920f3a7 position=1 id=1890011215, oldPos=-1, pLpos:-1 update tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{2b4f31d VFED.V... .......D 0,0-720,1120 #7f0a01e8 app:id/inbox_list}, adapter:awais.instagrabber.adapters.DirectMessageInboxAdapter@2416143, layout:androidx.recyclerview.widget.LinearLayoutManager@e4b03c0, context:awais.instagrabber.activities.MainActivity@5ede010
at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:27)
at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:21)
at androidx.recyclerview.widget.DefaultItemAnimator.endChangeAnimationIfNecessary(DefaultItemAnimator.java:8)
at androidx.recyclerview.widget.DefaultItemAnimator.endAnimations(DefaultItemAnimator.java:23)
at androidx.recyclerview.widget.RecyclerView.onDetachedFromWindow(RecyclerView.java:3)
at android.view.View.dispatchDetachedFromWindow(View.java:14623)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3100)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3092)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3092)
at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4759)
at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4732)
at android.view.ViewGroup.removeView(ViewGroup.java:4663)
at androidx.fragment.app.FragmentContainerView.removeView(FragmentContainerView.java:2)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:253)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:363)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
at androidx.fragment.app.FragmentManager.destroyFragmentView(FragmentManager.java:2)
at androidx.fragment.app.FragmentManager$2.onComplete(FragmentManager.java:8)
at androidx.fragment.app.FragmentAnim$2$1.run(FragmentAnim.java:3)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5628)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by ammargitham** [comment]
Seems to be a library issue.
