### ISSUE TITLE
[BUG] StoryFragment: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1554]
When I open a story and then tap a mention link to someone's profile, the app crashes.

Build 2cc15de on Android 9

Unfortunately both accounts are private. (I don't follow many people overall so I can't provide much info to reproduce, but still wanted to let you know.)

**Comment by ammargitham** [comment]
No crash log?

**Comment by Martin5001** [comment]
Not in the app no, will get adb crash dump when I get to my PC hopefully later this day. (I'm on mobile most of the time, sorry, just wanted to let you know as soon as possible in case you would already have something to grab on to.)

**Comment by Martin5001** [comment]
[logcat.txt](https://github.com/austinhuang0131/barinsta/files/6759796/logcat.txt)

**Comment by ammargitham** [comment]
Process: me.austinhuang.instagrabber, PID: 9805
 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at awais.instagrabber.fragments.StoryViewerFragment.openProfile(StoryViewerFragment.java:22)
        at awais.instagrabber.fragments.-$$Lambda$StoryViewerFragment$XhzYIuWuTbgOntoqNb6jmwnrGkA.onClick(lambda:1)
        at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1)
        at android.widget.AdapterView.performItemClick(AdapterView.java:362)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
        at android.widget.AbsListView$7.run(AbsListView.java:6612)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by austinhuang0131** [comment]
yeah i'll fix this as story viewmodel rewrite
