### ISSUE TITLE
[BUG] Fresco OOM

### ISSUE THREAD

**Issue by NitroNils** [austinhuang0131/barinsta#173]
## Environment

 See report

## Additional info

New Trace collected:
=====================
Error report collected on: Mon Sep 21 18:03:19 GMT+02:00 2020

Information:
==============
VERSION		: 19.0-a1
VERSION_CODE	: 50
PHONE-MODEL	: H60-L04
ANDROID_VERS	: 6.0
ANDROID_REL	: 23
BRAND			: Huawei
MANUFACTURER	: HUAWEI
BOARD			: H60-L04
DEVICE			: hwH60
PRODUCT		: H60-L04
HOST			: WUH1000017439
TAGS			: release-keys
INSTRUCTION	: Please attach details on how to produce this crash. Your help is appreciated.
PRIVACY    	: Your email address and crash report will be made PUBLIC on the GitHub repository.

Stack:
==============
java.lang.OutOfMemoryError: Failed to allocate a 2811012 byte allocation with 2560672 free bytes and 2MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:859)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:829)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:796)
	at com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:55)
	at com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:27)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:254)
	at com.facebook.imagepipeline.platform.DefaultDecoder.decodeFromStream(DefaultDecoder.java:217)
	at com.facebook.imagepipeline.platform.DefaultDecoder.decodeJPEGFromEncodedImageWithColorSpace(DefaultDecoder.java:155)
	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java:179)
	at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:58)
	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:120)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.internalDecode(DecodeProducer.java:382)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java

**Comment by austinhuang0131** [comment]
out of memory?!

you might wanna explain what were you trying to do

**Comment by ammargitham** [comment]
Closing as no one else has reported this and cannot be reproduce. Will re-open if we get more info.
