### ISSUE TITLE
[BUG] App crash report 

### ISSUE THREAD

**Issue by tryb3l** [austinhuang0131/barinsta#1746]
## Steps

1. open barinsta app 
2. Open Stories 
3. Tap share icon 
4. App crashes 

## Environment

 - Device:  Google Pixel 4a5g
 - Android version: 11 

## Additional info

 New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at https://github.com/austinhuang0131/barinsta/issues.

When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-25T00:09:47.408

Information:
==============
VERSION		    : 19.2.4-fdroid
VERSION_CODE	: 65
PHONE-MODEL	    : Pixel 4a (5G)
ANDROID_VERS	: 11
ANDROID_REL	    : 30
BRAND			: google
MANUFACTURER	: Google
BOARD			: bramble
DEVICE			: bramble
PRODUCT		    : bramble
HOST			: abfarm-01379
TAGS			: release-keys

Stack:
==============
java.lang.IllegalArgumentException: User is not logged in!
	at awais.instagrabber.viewmodels.UserSearchViewModel.<init>(UserSearchViewModel.java:19)
	at java.lang.Class.newInstance(Native Method)
	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:1)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:7)
	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:5)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:14)
	at awais.instagrabber.fragments.UserSearchFragment.getViewModel(UserSearchFragment.kt:1)
	at awais.instagrabber.fragments.UserSearchFragment.onViewCreated(UserSearchFragment.kt:9)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:42)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:134)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

*** End of current Report ***

**Comment by austinhuang0131** [comment]
Practically the same as #1747 since (as you can see) you have a login issue
