### ISSUE TITLE
[BUG] v19.x Bugs

### ISSUE THREAD

**Issue by RickyM7** [austinhuang0131/barinsta#489]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

## Bugs

Bugs found in v19.0.4:

- [ ] 1. The string "added_to_favs_short" is not being used, instead the string "added_to_favs" is being used.

- [x] 2. **[Fixed in v19.0.5]** ~~Crash while trying to see who liked the comment (Anonymous mode only).~~

- [x] 3. **[Fixed in v19.0.5]** ~~Crash while exploring tagged posts.~~

## Steps

Steps to crash the app:

- `2.`:
1. Go to 'a comment with at least one like in any post'
2. Click on 'View comment likers'
3. See error

- `3.`:
1. Open the tagged posts page of any profile and scroll down quickly
2. See error

## Environment

- Device: Redmi Note 4
- Android version: MIUI 11 (Android 7.0)
- App version: v19.0.5

### Crash Logs

- `2.` (Comment Likers):

New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: Thu Dec 31 17:39:25 GMT-03:00 2020

Information:
==============
VERSION		: 19.0.4
VERSION_CODE	: 56
PHONE-MODEL	: Redmi Note 4
ANDROID_VERS	: 7.0
ANDROID_REL	: 24
BRAND			: xiaomi
MANUFACTURER	: Xiaomi
BOARD			: msm8953
DEVICE			: mido
PRODUCT		: mido
HOST			: mi-server
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.recyclerview.widget.RecyclerView$LayoutManager.getItemCount()' on a null object reference
	at awais.instagrabber.customviews.helpers.RecyclerLazyLoader.onScrolled(RecyclerLazyLoader.java:1)
	at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:10)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:130)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:27)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:60)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:27)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
	at android.view.View.layout(View.java:17551)
	at android.view.ViewGroup.layout(ViewGroup.java:5614)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2386)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2113)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1290)
	at android.view.ViewRootImpl$TraversalRunnab

le.run(ViewRootImpl.java:6399)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
	at android.view.Choreographer.doCallbacks(Choreographer.java:685)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

Cause:
==============

**** End of current Report ***

- `3.` (Tagged):

New Trace collected:

IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: Thu Dec 31 21:20:02 GMT-03:00 2020

Information:

VERSION		: 19.0.4
VERSION_CODE	: 56
PHONE-MODEL	: Redmi Note 4
ANDROID_VERS	: 7.0
ANDROID_REL	: 24
BRAND			: xiaomi
MANUFACTURER	: Xiaomi
BOARD			: msm8953
DEVICE			: mido
PRODUCT		: mido
HOST			: mi-server
TAGS			: release-keys

Stack:

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
at awais.instagrabber.adapters.FeedAdapterV2$1.areContentsTheSame(FeedAdapterV2.java:5)
at androidx.recyclerview.widget.AsyncListDiffer$1$1.areContentsTheSame(AsyncListDiffer.java:5)
at androidx.recyclerview.widget.DiffUtil$DiffResult.(DiffUtil.java:19)
at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:75)
at androidx.recyclerview.widget.AsyncListDiffer$1.run(AsyncListDiffer.java:1)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:760)

Cause:

**** End of current Report ****

**Comment by austinhuang0131** [comment]
1. ok
2. Can't reproduce, gonna need to know the background

**Comment by RickyM7** [comment]
> 2. Can't reproduce, gonna need to know the background

I don't understand, what more information do you need?

And here below is another crash log. This time the crash occurred while browsing through the posts in "Tagged", but specifically this occurs when you reach the end of the page before new posts load, if you try to drag down the crash will occur.

New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: Thu Dec 31 21:20:02 GMT-03:00 2020

Information:
==============
VERSION		: 19.0.4
VERSION_CODE	: 56
PHONE-MODEL	: Redmi Note 4
ANDROID_VERS	: 7.0
ANDROID_REL	: 24
BRAND			: xiaomi
MANUFACTURER	: Xiaomi
BOARD			: msm8953
DEVICE			: mido
PRODUCT		: mido
HOST			: mi-server
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
	at awais.instagrabber.adapters.FeedAdapterV2$1.areContentsTheSame(FeedAdapterV2.java:5)
	at androidx.recyclerview.widget.AsyncListDiffer$1$1.areContentsTheSame(AsyncListDiffer.java:5)
	at androidx.recyclerview.widget.DiffUtil$DiffResult.<init>(DiffUtil.java:19)
	at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:75)
	at androidx.recyclerview.widget.AsyncListDiffer$1.run(AsyncListDiffer.java:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

Cause:
==============

**** End of current Report ***

**Comment by RickyM7** [comment]
@austinhuang0131 About 1.: When you click to add a profile to the favorites the string that appears is `added_to_favs`, but when you exit and re-enter the favorite profile, the string is shown is the `added_to_favs_short` (which is expected). That's a little weird.

**Comment by RickyM7** [comment]
> When you click to add a profile to the favorites the string that appears is added_to_favs, but when you exit and re-enter the favorite profile, the string is shown is the added_to_favs_short (which is expected). That's a little weird.

@austinhuang0131 This still continues on v19.0.5.
