### ISSUE TITLE
[BUG] Crash when trying to open Feed

### ISSUE THREAD

**Issue by RickyM7** [austinhuang0131/barinsta#689]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

The app crashes when you try to open Feed.

## Steps

1. Open Barinsta, go to the Feed tab and wait (if your home page is Feed you just need to open the app and wait)
2. See error

## Environment

 - Device: Redmi Note 4
 - Android version: MIUI 11 (Android 7.0)

## Additional info

New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: Sat Feb 13 16:43:31 GMT-03:00 2021

Information:
==============
VERSION		: 19.1.0-a1
VERSION_CODE	: 58
PHONE-MODEL	: Redmi Note 4
ANDROID_VERS	: 7.0
ANDROID_REL	: 24
BRAND			: xiaomi
MANUFACTURER	: Xiaomi
BOARD			: msm8953
DEVICE			: mido
PRODUCT		: mido
HOST			: mi-server
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String awais.instagrabber.repositories.responses.Location.getName()' on a null object reference
	at awais.instagrabber.adapters.FeedAdapterV2.onBindViewHolder(FeedAdapterV2.java:83)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:164)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:15)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:140)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:1)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:23)
	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:6)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
	at android.view.Choreographer.doCallbacks(Choreographer.java:685)
	at android.view.Choreographer.doFrame(Choreographer.java:618)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

Cause:
==============

**** End of current Report ***

**Comment by 4n0nym0u53** [comment]
For me it doesn't crash, but it just can't load. I'm on a OnePlus 8T.

**Comment by Kanval87** [comment]
Hey Guys, i am trying to reproduce this bug but seems unable to. i tried phone as well as simulator... may be the account(mine) i am trying does not have enough data.

**Comment by RickyM7** [comment]
@Kanval87 I do not know. My account has few things too (I think in my feed has about 40 posts).

**Comment by Kanval87** [comment]
i am gonna play around with bug a bit more to inspect, will update you guys 👍
