### ISSUE TITLE
[BUG] Suggested Users crashes the app

### ISSUE THREAD

**Issue by Smponi** [austinhuang0131/barinsta#834]
-  [x] My app is on the latest version. I understand that any other version is not supported.
-  [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

Clicking on _suggested users_ in the _more_ tab crashes the app.
## Steps

1. Open the app
2. Click on more
3. Suggested users
## Environment

 - Device: Pixel 3a
 - Android version: 11
 - Barinsta version: 19.1.0(60)
 
 ## Stack:
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
	at java.util.ArrayList.addAll(ArrayList.java:588)
	at awais.instagrabber.webservices.NewsService$3.onResponse(NewsService.java:5)
	at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(lambda:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by austinhuang0131** [comment]
Not reproducible. Please provide crash dump.

**Comment by Smponi** [comment]
Added the stack trace to issue
