### ISSUE TITLE
[BUG] Crash on opening DM thread with view-once image in its history

### ISSUE THREAD

**Issue by sigaloid** [austinhuang0131/barinsta#839]
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.
Simply opened a DM thread that contained an image. It was sent as "view-once" if that matters. This thread crashes even once the image is opened and is reproducible  (non instagram user)
Error report collected on: Sun Mar 21 20:24:35 EDT 2021

Information:
==============
VERSION		: 19.1.0
VERSION_CODE	: 60
PHONE-MODEL	: LM-G710VM
ANDROID_VERS	: 9
ANDROID_REL	: 28
BRAND			: lge
MANUFACTURER	: LGE
BOARD			: sdm845
DEVICE			: judyln
PRODUCT		: judyln_vzw
HOST			: LGEACI5R9
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to read from field 'int awais.instagrabber.models.enums.DirectItemType.id' on a null object reference
	at awais.instagrabber.adapters.DirectItemsAdapter.getItemViewType(DirectItemsAdapter.java:6)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:76)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:102)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:23)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:774)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2907)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2416)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1530)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7533)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1025)
	at android.view.Choreographer.doCallbacks(Choreographer.java:836)
	at android.view.Choreographer.doFrame(Choreographer.java:771)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1011)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6854)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

Cause:
==============

**** End of current Report ***
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: Sun Mar 21 20:24:42 EDT 2021

Information:
==============
VERSION		: 19.1.0
VERSION_CODE	: 60
PHONE-MODEL	: LM-G710VM
ANDROID_VERS	: 9
ANDROID_REL	: 28
BRAND			: lge
MANUFACTURER	: LGE
BOARD			: sdm845
DEVICE			: judyln
PRODUCT		: judyln_vzw
HOST			: LGEACI5R9
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to read from field 'int awais.instagrabber.models.enums.DirectItemType.id' on a null object reference
	at awais.instagrabber.adapters.DirectItemsAdapter.getItemViewType(DirectItemsAdapter.java:6)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:76)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:102)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:23)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:774)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2907)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2416)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1530)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7533)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1025)
	at android.view.Choreographer.doCallbacks(Choreographer.java:836)
	at android.view.Choreographer.doFrame(Choreographer.java:771)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1011)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6854)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

Cause:
==============

**** End of current Report ***
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: Sun Mar 21 20:24:47 EDT 2021

Information:
==============
VERSION		: 19.1.0
VERSION_CODE	: 60
PHONE-MODEL	: LM-G710VM
ANDROID_VERS	: 9
ANDROID_REL	: 28
BRAND			: lge
MANUFACTURER	: LGE
BOARD			: sdm845
DEVICE			: judyln
PRODUCT		: judyln_vzw
HOST			: LGEACI5R9
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to read from field 'int awais.instagrabber.models.enums.DirectItemType.id' on a null object reference
	at awais.instagrabber.adapters.DirectItemsAdapter.getItemViewType(DirectItemsAdapter.java:6)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:76)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:102)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:23)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:774)
	at android.view.View.layout(View.java:20740)
	at android.view.ViewGroup.layout(ViewGroup.java:6268)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2907)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2416)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1530)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7533)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1025)
	at android.view.Choreographer.doCallbacks(Choreographer.java:836)
	at android.view.Choreographer.doFrame(Choreographer.java:771)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1011)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6854)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

Cause:
==============

**** End of current Report ***

**Comment by austinhuang0131** [comment]
Is that picture already expired?

**Comment by sigaloid** [comment]
It was not, no.

**Comment by austinhuang0131** [comment]
Then it's probably not caused by that picture. Are there other messages?

**Comment by sigaloid** [comment]
Only a few regular attachments and text messages. I have since deleted it though, since it kept crashing when I opened that thread. I can ask them to resend a photo and see if I can reproduce it though

**Comment by sigaloid** [comment]
Doesn't crash now, same person, same once-view image. feel free to close as it seemed to be one-time for that one image
